runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always

    # All files with extensions are considered static
  - url: /(.+\..+)
    static_files: \1
    upload: (.*)
    secure: always

    # The rest are folders
  - url: /(.*)/
    static_files: \1/index.html
    upload: (.+)/index.html
    secure: always
  - url: /(.*)
    static_files: \1/index.html
    upload: (.+)/index.html
    secure: always
