runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: index.html
    upload: index.html
  - url: /(.+)/
    static_files: \1/index.html
    upload: (.+)/index.html
    secure: always
  - url: /(.*)
    static_files: \1
    upload: (.*)
    secure: always
